'------------------------------------------------------------------------------
'<auto-generated>
' Generated by the DevExpress.Blazor package.
' To prevent this operation, add the DxExtendStartupHost property to the project and set this property to False.
'
' MySolution.Blazor.Server.csproj:
'
' <Project Sdk="Microsoft.NET.Sdk.Web">
'  <PropertyGroup>
'    <TargetFramework>net5.0</TargetFramework>
'    <DxExtendStartupHost>False</DxExtendStartupHost>
'  </PropertyGroup>
'</auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports Microsoft.Extensions.DependencyInjection
Imports Microsoft.AspNetCore.Hosting

<Assembly: HostingStartup(GetType(MySolution.Blazor.Server.DevExpressHostingStartup))>

Namespace MySolution.Blazor.Server
	Partial Public Class DevExpressHostingStartup
		Implements IHostingStartup

		Private Sub IHostingStartup_Configure(ByVal builder As IWebHostBuilder) Implements IHostingStartup.Configure
			builder.ConfigureServices(Sub(serviceCollection)
				serviceCollection.AddDevExpressBlazor()
			End Sub)
		End Sub
	End Class
End Namespace
